// project/book-library/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Làm bạn với bầu trời';

  thumbnailUrl = 'https://salt.tikicdn.com/cache/w1200/ts/product/af/a1/4b/92477ec9b6688060b2b5d2022a60d3e6.jpg';

  summary = 'Một câu chuyện giản dị, chứa đầy bất ngờ cho tới trang cuối cùng';

  author = 'Nguyễn Nhật Ánh';

  commentNumber = 35;

  rating = 5;

  sourceName = 'Tiki';
}

<div class="row">
  <div class="col search-bar-container">
    <search-form (searchAction)="search($event)"> </search-form>
  </div>
</div>
<div class="row">
  <div class="col">
    <div *ngIf="books.length > 0">
      <ng-container *ngFor="let book of books">
        <ng-container *ngIf="book.details && book.details.length > 0">
          <ng-container *ngIf="book.details[0].source === 'AAHCM'">
            <div class="book-list-item">
              <angular-book-summary-tile
                [id]="book.id"
                [title]="book.name"
                [thumbnailUrl]="book.details[0].coverUrl || 'assets/empty-thumbnail-placeholder.png'"
                [summary]="book.details[0].description"
                [author]="book.author"
                [commentNumber]="book.details[0].comments?.length"
                [rating]="5"
                [sourceName]="book.details[0].source"
                (clicked)="onClicked($event)"
              ></angular-book-summary-tile>
            </div>
          </ng-container>
          <ng-container *ngIf="book.details[0].source !== 'AAHCM'">
            <div class="book-list-item">
              <react-book-summary-tile
                [id]="book.id"
                [title]="book.name"
                [thumbnailUrl]="book.details[0].coverUrl || 'assets/empty-thumbnail-placeholder.png'"
                [summary]="book.details[0].description"
                [author]="book.author"
                [commentNumber]="book.details[0].comments?.length"
                [rating]="5"
                [sourceName]="book.details[0].source"
                (clicked)="onClicked($event)"
              ></react-book-summary-tile>
            </div>
          </ng-container>
        </ng-container>
      </ng-container>
    </div>
  </div>
</div>

// project/react-book-summary-tile/src/App.js
import bootstrap from "bootstrap/dist/css/bootstrap.min.css";
import fontawesome from "font-awesome/css/font-awesome.css";
import React from "react";
import Style from "style-it";

import styles from "./App.css";
import { propTypes } from "./componentProperties";

const App = props => {
  /*
   * This is a workaround to import external css files as @import does not work properly
   */
  const cssStyles = styles
    .toString()
    .concat(fontawesome.toString())
    .concat(bootstrap.toString());

  return (
    <Style>
      {cssStyles.toString()}
      <div className="app">
        <div className="container">
          <div className="row">
            <div className="col col-sm-2 thumbnail">
              <img
                src="https://salt.tikicdn.com/cache/w1200/ts/product/af/a1/4b/92477ec9b6688060b2b5d2022a60d3e6.jpg"
                className="img-fluid"
                alt="Book Thumbnail"
              />
            </div>
            <div className="col summary">
              <h1>
                <strong>{props.componentTitle}</strong>
              </h1>
              <blockquote className="blockquote">
                <p className="mb-0 text-muted">
                  Một câu chuyện giản dị, chứa đầy bất ngờ cho tới trang cuối
                  cùng
                </p>
                <footer className="blockquote-footer">
                  <strong>Nguyễn Nhật Ánh</strong>
                </footer>
              </blockquote>
              <div className="footer">
                <span className="rating text-warning">
                  <i className="fa fa-star" />
                  <i className="fa fa-star" />
                  <i className="fa fa-star" />
                  <i className="fa fa-star" />
                  <i className="fa fa-star" />
                </span>
                <strong>
                  Bình luận (<i className="text-muted">35</i>)
                </strong>
                <strong>Nguồn: Tiki</strong>
              </div>
            </div>
          </div>
        </div>
      </div>
    </Style>
  );
};

App.propTypes = propTypes;

export default App;
